using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Net.Security;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace COMP3602Assign07
{
    public partial class MainForm : Form
    {
        private ClientViewModel clientVM;
        public MainForm()
        {
            InitializeComponent();
        }

        private void MainForm_Load(object sender, EventArgs e)
        {
            PrintLabel();

            /*labelProductLegend = string.Format("{0}\r\n{1}\r\n{2}\r\n",
                                    "Total YTD Sales",
                                    "Taxable Clients",
                                    "Cliets with Credit Hold");*/

            clientVM = new ClientViewModel(0.05m, 0.07m);
            setBindings();
            setupDataGridView();

        }
        
        private void setBindings()
        {
            textBoxCompanyName.DataBindings.Add("Text", clientVM, "DisplayProduct.CompanyName");
            textBoxAddress1.DataBindings.Add("Text", clientVM, "DisplayProduct.Address1");
            textBoxAddress2.DataBindings.Add("Text", clientVM, "DisplayProduct.Address2");
            textBoxCity.DataBindings.Add("Text", clientVM, "DisplayProduct.City");
            textBoxProvince.DataBindings.Add("Text", clientVM, "DisplayProduct.Province");
            textBoxPostalCode.DataBindings.Add("Text", clientVM, "DisplayProduct.PostalCode");
            textBoxYTDSales.DataBindings.Add("Text", clientVM, "DisplayProduct.YTDSales");
            textBoxCreditHold.DataBindings.Add("Text", clientVM, "DisplayProduct.CreditHold");
            textBoxNotes.DataBindings.Add("Text", clientVM, "DisplayProduct.Notes");
            textBoxIsTaxable.DataBindings.Add("Text", clientVM, "DisplayProduct.IsTaxable");

            //labelCount.DataBindings.Add("Text", clientVM, "Count");
            //labelTotals.DataBindings.Add("Text", clientVM, "Totals");

            //dataGridViewProducts.AutoGeneratedColumns = false;
            //dataGridViewProducts.DataSource = clientVM.ClientsSource;
        }

        private void PrintLabel()
        {
            List<Client> clientsList = ClientRepository.GetCustomerLocations();
            string clientInfo = "";
            foreach(Client client in clientsList)
            {
                clientInfo += client.ToString() + "\n";
            }

            labelDisplay.Text = clientInfo;
        }

        private void setupDataGridView()
        {
            // configure for readonly 
            /*dataGridViewProducts.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dataGridViewProducts.MultiSelect = false;
            dataGridViewProducts.AllowUserToAddRows = false;
            dataGridViewProducts.EditMode = DataGridViewEditMode.EditProgrammatically;
            dataGridViewProducts.AllowUserToOrderColumns = false;
            dataGridViewProducts.AllowUserToResizeColumns = false;
            dataGridViewProducts.AllowUserToResizeRows = false;
            dataGridViewProducts.ColumnHeadersDefaultCellStyle.Font = new Font(DataGridView.DefaultFont, FontStyle.Bold);
            dataGridViewProducts.RowHeadersVisible = false;
*/

            // add columns

            DataGridViewTextBoxColumn companyName = new DataGridViewTextBoxColumn();
            companyName.Name = "companyName";
            companyName.DataPropertyName = "CompanyName";
            companyName.HeaderText = "CompanyName";
            companyName.Width = 40;
            companyName.HeaderCell.Style.Alignment = DataGridViewContentAlignment.MiddleRight;
            companyName.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            companyName.SortMode = DataGridViewColumnSortMode.NotSortable;
            //dataGridViewProducts.Columns.Add(companyName);

            DataGridViewTextBoxColumn address1 = new DataGridViewTextBoxColumn();
            address1.Name = "address1";
            address1.DataPropertyName = "Address1";
            address1.HeaderText = "Address1";
            address1.Width = 90;
            address1.SortMode = DataGridViewColumnSortMode.NotSortable;
            //dataGridViewProducts.Columns.Add(address1);


            DataGridViewTextBoxColumn address2 = new DataGridViewTextBoxColumn();
            address2.Name = "desc";
            address2.DataPropertyName = "Description";
            address2.HeaderText = "Description";
            address2.Width = 220;
            address2.SortMode = DataGridViewColumnSortMode.NotSortable;
            address2.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            //dataGridViewProducts.Columns.Add(address2);


            DataGridViewTextBoxColumn city = new DataGridViewTextBoxColumn();
            city.Name = "city";
            city.DataPropertyName = "City";
            city.HeaderText = "City";
            city.Width = 220;
            city.SortMode = DataGridViewColumnSortMode.NotSortable;
            city.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            //dataGridViewProducts.Columns.Add(city);

            DataGridViewTextBoxColumn province = new DataGridViewTextBoxColumn();
            province.Name = "province";
            province.DataPropertyName = "Province";
            province.HeaderText = "Province";
            province.Width = 220;
            province.SortMode = DataGridViewColumnSortMode.NotSortable;
            province.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            //dataGridViewProducts.Columns.Add(province);

            DataGridViewTextBoxColumn postalCode = new DataGridViewTextBoxColumn();
            postalCode.Name = "postalCode";
            postalCode.DataPropertyName = "PostalCode";
            postalCode.HeaderText = "PostalCode";
            postalCode.Width = 220;
            postalCode.SortMode = DataGridViewColumnSortMode.NotSortable;
            postalCode.AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill;
            //dataGridViewProducts.Columns.Add(postalCode);

            DataGridViewTextBoxColumn ytdSales = new DataGridViewTextBoxColumn();
            ytdSales.Name = "ytdSales";
            ytdSales.DataPropertyName = "YTDSales";
            ytdSales.HeaderText = "YTDSales";
            ytdSales.Width = 80;
            ytdSales.HeaderCell.Style.Alignment = DataGridViewContentAlignment.MiddleRight;
            ytdSales.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            ytdSales.DefaultCellStyle.Format = "N2";
            ytdSales.SortMode = DataGridViewColumnSortMode.NotSortable;
            //dataGridViewProducts.Columns.Add(ytdSales);

            DataGridViewTextBoxColumn creditHold = new DataGridViewTextBoxColumn();
            creditHold.Name = "creditHold";
            creditHold.DataPropertyName = "CreditHold";
            creditHold.HeaderText = "CreditHold";
            creditHold.Width = 80;
            creditHold.HeaderCell.Style.Alignment = DataGridViewContentAlignment.MiddleRight;
            creditHold.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            creditHold.DefaultCellStyle.Format = "N2";
            creditHold.SortMode = DataGridViewColumnSortMode.NotSortable;
            //dataGridViewProducts.Columns.Add(creditHold);

            DataGridViewTextBoxColumn notes = new DataGridViewTextBoxColumn();
            notes.Name = "notes";
            notes.DataPropertyName = "Notes";
            notes.HeaderText = "Notes";
            notes.Width = 80;
            notes.HeaderCell.Style.Alignment = DataGridViewContentAlignment.MiddleRight;
            notes.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            notes.DefaultCellStyle.Format = "N2";
            notes.SortMode = DataGridViewColumnSortMode.NotSortable;
            //dataGridViewProducts.Columns.Add(notes);

            DataGridViewTextBoxColumn isTaxable = new DataGridViewTextBoxColumn();
            isTaxable.Name = "isTaxable";
            isTaxable.DataPropertyName = "IsTaxable";
            isTaxable.HeaderText = "IsTaxable";
            isTaxable.Width = 80;
            isTaxable.HeaderCell.Style.Alignment = DataGridViewContentAlignment.MiddleRight;
            isTaxable.DefaultCellStyle.Alignment = DataGridViewContentAlignment.MiddleRight;
            isTaxable.DefaultCellStyle.Format = "N2";
            isTaxable.SortMode = DataGridViewColumnSortMode.NotSortable;
            //dataGridViewProducts.Columns.Add(isTaxable);
        }
    }
}
